// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ranko.Resources.Database;

namespace Ranko.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    partial class SqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("Ranko.Resources.Database.AdminRoleEntity", b =>
                {
                    b.Property<ulong>("RoleId");

                    b.Property<ulong>("GuildId");

                    b.HasKey("RoleId");

                    b.HasIndex("GuildId");

                    b.ToTable("AdminRoles");
                });

            modelBuilder.Entity("Ranko.Resources.Database.GuildConfigEntity", b =>
                {
                    b.Property<ulong>("GuildId");

                    b.Property<ulong>("AlertChannelId");

                    b.Property<ulong>("CommandChannelId");

                    b.Property<ushort>("DateFormat");

                    b.Property<string>("DefaultTimezone");

                    b.Property<uint>("DeleteAlertMessageTimespan");

                    b.Property<ushort>("Language");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfig");
                });

            modelBuilder.Entity("Ranko.Resources.Database.TaskEntity", b =>
                {
                    b.Property<ulong>("TaskId")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("AssignedUserId");

                    b.Property<uint>("CompletionStatus");

                    b.Property<DateTime>("DeadlineDate");

                    b.Property<string>("Description");

                    b.Property<ulong>("GuildId");

                    b.Property<DateTime>("LastAlertDate");

                    b.Property<string>("Name");

                    b.Property<string>("TimeZone");

                    b.HasKey("TaskId");

                    b.HasIndex("GuildId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Ranko.Resources.Database.AdminRoleEntity", b =>
                {
                    b.HasOne("Ranko.Resources.Database.GuildConfigEntity", "Guild")
                        .WithMany("AdminRoles")
                        .HasForeignKey("GuildId")
                        .HasConstraintName("ForeignKey_AdminRoleEntity_GuildConfigEntity")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ranko.Resources.Database.TaskEntity", b =>
                {
                    b.HasOne("Ranko.Resources.Database.GuildConfigEntity", "Guild")
                        .WithMany("Tasks")
                        .HasForeignKey("GuildId")
                        .HasConstraintName("ForeignKey_TaskEntity_GuildConfigEntity")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
